language: node_js
branches:
  only:
  - master
  - 0.2.0
notifications:
  slack:
    secure: 4V7/n8uUJTvR8X7lO9E7EcXhabsyCqH/Ix1hANLWR9WecHcxoVXukcMKemvuMtwtickp98jOa5IsOBTcpenguOpWr5oHV2WK6ZODMand+QLg+0NgtNmxxOwK3baDPN9/LMc5bwsi+zfH300TMXQfDhENp/xDfUg+QrDhtn4oHHI=
  email:
  - PhoneGapCI@adobe.com
